/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AsamUiModule extends AbstractAsamUiModule {

	public AsamUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
