/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.asam;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete By Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.asam.asam.DeleteByMethod#getProperty <em>Property</em>}</li>
 *   <li>{@link org.xtext.example.asam.asam.DeleteByMethod#getPtype <em>Ptype</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.asam.asam.AsamPackage#getDeleteByMethod()
 * @model
 * @generated
 */
public interface DeleteByMethod extends EObject
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' attribute.
   * @see #setProperty(String)
   * @see org.xtext.example.asam.asam.AsamPackage#getDeleteByMethod_Property()
   * @model
   * @generated
   */
  String getProperty();

  /**
   * Sets the value of the '{@link org.xtext.example.asam.asam.DeleteByMethod#getProperty <em>Property</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' attribute.
   * @see #getProperty()
   * @generated
   */
  void setProperty(String value);

  /**
   * Returns the value of the '<em><b>Ptype</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.asam.asam.VTypes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ptype</em>' attribute.
   * @see org.xtext.example.asam.asam.VTypes
   * @see #setPtype(VTypes)
   * @see org.xtext.example.asam.asam.AsamPackage#getDeleteByMethod_Ptype()
   * @model
   * @generated
   */
  VTypes getPtype();

  /**
   * Sets the value of the '{@link org.xtext.example.asam.asam.DeleteByMethod#getPtype <em>Ptype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ptype</em>' attribute.
   * @see org.xtext.example.asam.asam.VTypes
   * @see #getPtype()
   * @generated
   */
  void setPtype(VTypes value);

} // DeleteByMethod
