/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.asam;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.asam.asam.AsamPackage#getListType()
 * @model
 * @generated
 */
public interface ListType extends Type, RType
{
} // ListType
