/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.asam;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.asam.asam.Relationship#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.asam.asam.Relationship#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.asam.asam.Relationship#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.asam.asam.AsamPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends Element
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.asam.asam.dbRelations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.asam.asam.dbRelations
   * @see #setType(dbRelations)
   * @see org.xtext.example.asam.asam.AsamPackage#getRelationship_Type()
   * @model
   * @generated
   */
  dbRelations getType();

  /**
   * Sets the value of the '{@link org.xtext.example.asam.asam.Relationship#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.asam.asam.dbRelations
   * @see #getType()
   * @generated
   */
  void setType(dbRelations value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Entity)
   * @see org.xtext.example.asam.asam.AsamPackage#getRelationship_Source()
   * @model
   * @generated
   */
  Entity getSource();

  /**
   * Sets the value of the '{@link org.xtext.example.asam.asam.Relationship#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Entity value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Entity)
   * @see org.xtext.example.asam.asam.AsamPackage#getRelationship_Target()
   * @model
   * @generated
   */
  Entity getTarget();

  /**
   * Sets the value of the '{@link org.xtext.example.asam.asam.Relationship#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Entity value);

} // Relationship
