/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.asam.ui.internal.AsamActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AsamExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AsamActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AsamActivator activator = AsamActivator.getInstance();
		return activator != null ? activator.getInjector(AsamActivator.ORG_XTEXT_EXAMPLE_ASAM_ASAM) : null;
	}

}
