/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAsamScopeProvider extends DelegatingScopeProvider {
}
