/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.asam.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.asam.asam.AsamPackage;
import org.xtext.example.asam.asam.RepositoryMethod;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Repository Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RepositoryMethodImpl extends MinimalEObjectImpl.Container implements RepositoryMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RepositoryMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsamPackage.Literals.REPOSITORY_METHOD;
  }

} //RepositoryMethodImpl
