/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.asam.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.asam.parser.antlr.internal.InternalAsamParser;
import org.xtext.example.asam.services.AsamGrammarAccess;

public class AsamParser extends AbstractAntlrParser {

	@Inject
	private AsamGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAsamParser createParser(XtextTokenStream stream) {
		return new InternalAsamParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Sboot";
	}

	public AsamGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AsamGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
