import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { SbootGeneratedModule, SbootGeneratedSharedModule } from './generated/module.js';
import { SbootValidator, registerValidationChecks } from './sboot-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SbootAddedServices = {
    validation: {
        SbootValidator: SbootValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SbootServices = LangiumServices & SbootAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SbootModule: Module<SbootServices, PartialLangiumServices & SbootAddedServices> = {
    validation: {
        SbootValidator: () => new SbootValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSbootServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Sboot: SbootServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SbootGeneratedSharedModule
    );
    const Sboot = inject(
        createDefaultModule({ shared }),
        SbootGeneratedModule,
        SbootModule
    );
    shared.ServiceRegistry.register(Sboot);
    registerValidationChecks(Sboot);
    return { shared, Sboot };
}
